name: build
on:
  pull_request:
    branches:
     - '**'
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-tidy
      - name: Set up Python PIP
        run: |
          python -m pip install --upgrade pip
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.12
        with:
          cmake-version: '3.23.x'
      - name: Install Conan
        id: conan
        uses: turtlebrowser/get-conan@main
      - name: Configure project
        run: |          
          cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release
      - name: Build project
        run: |          
          cmake --build build
      - name: Run unit tests
        run: |                
          valgrind cmake --build build --target test
